base_dev_dir: null

hydra:
  run:
    dir: '${base_dev_dir}/xskill/experiment/label_real_kitchen/${now:%Y-%m-%d_%H-%M-%S}'

exp_path: null
save_path: ${exp_path}
ckpt: 299
device: 'cuda:0'



resize_shape: [160,120]
frequency: 3

robot_dataset:
  _target_: xskill.dataset.real_world_pretrain_dataset.RealWorldEpisodeTrajDataset
  _allowed_dirs: [
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/draw_cloth_oven',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/draw_cloth_light',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/draw_light_cloth',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/draw_light_oven',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/light_cloth_oven',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/light_draw_cloth',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/light_oven_draw',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/oven_light_cloth',
  ]
  frame_sampler:
    _target_: xskill.dataset.frame_samplers.ZarrFrequencySampler
    offset: 0
    num_frames: -1
    frequency: 3
  slide: 8
  max_get_threads: 50
  resize_shape: ${resize_shape}

human_dataset:
  _target_: xskill.dataset.real_world_pretrain_dataset.RealWorldEpisodeTrajDataset
  _allowed_dirs: [
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/human_draw_cloth_oven',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/human_cloth_light_oven',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/human_cloth_oven_light',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/human_draw_cloth_light',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/human_draw_light_cloth',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/human_draw_light_oven',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/human_light_cloth_oven',
    '${base_dev_dir}/xskill/datasets/realworld_kitchen_dataset/data_v2/human_oven_draw_cloth',
  ]
  frame_sampler:
    _target_: xskill.dataset.frame_samplers.ZarrFrequencySampler
    offset: 0
    num_frames: ${robot_dataset.frame_sampler.num_frames}
    frequency: ${robot_dataset.frame_sampler.frequency}
  slide: 8
  max_get_threads: ${robot_dataset.max_get_threads}
  resize_shape: ${resize_shape}

augmentations: ['center_crop_110_146','normalize']

